### ISSUE TITLE
make test failed ` permission denied` on macos 11.6.5

### ISSUE THREAD

**Issue by ikaven1024** [karmada-io/karmada#1789]
**What happened**:
`make test` failed:
```
=== RUN   Test_GroupClustersWithScore
--- FAIL: Test_GroupClustersWithScore (0.00s)
panic: permission denied [recovered]
        panic: permission denied

goroutine 15 [running]:
testing.tRunner.func1.2({0x101f1a760, 0x102b79c68})
        /Users/didi/sdk/go1.17.5/src/testing/testing.go:1209 +0x348
testing.tRunner.func1(0xc0006036c0)
        /Users/didi/sdk/go1.17.5/src/testing/testing.go:1212 +0x2e4
panic({0x101f1a760, 0x102b79c68})
        /Users/didi/sdk/go1.17.5/src/runtime/panic.go:1052 +0x2ac
github.com/agiledragon/gomonkey/v2.modifyBinary(0x101b39a70, {0xc000132798, 0x18, 0x18})
        /Users/didi/OpenSouorce/karmada/vendor/github.com/agiledragon/gomonkey/v2/modify_binary_darwin.go:9 +0x150
github.com/agiledragon/gomonkey/v2.replace(0x101b39a70, 0x102070018)
        /Users/didi/OpenSouorce/karmada/vendor/github.com/agiledragon/gomonkey/v2/patch.go:255 +0x100
github.com/agiledragon/gomonkey/v2.(*Patches).ApplyCore(0xc0000e1770, {0x101ec08c0, 0x102070030, 0x13}, {0x101ec08c0, 0x102070018, 0x13})
        /Users/didi/OpenSouorce/karmada/vendor/github.com/agiledragon/gomonkey/v2/patch.go:217 +0x214
github.com/agiledragon/gomonkey/v2.(*Patches).ApplyFunc(0xc0000e1770, {0x101ec08c0, 0x102070030}, {0x101ec08c0, 0x102070018})
        /Users/didi/OpenSouorce/karmada/vendor/github.com/agiledragon/gomonkey/v2/patch.go:82 +0x318
github.com/agiledragon/gomonkey/v2.ApplyFunc(...)
        /Users/didi/OpenSouorce/karmada/vendor/github.com/agiledragon/gomonkey/v2/patch.go:24
github.com/karmada-io/karmada/pkg/scheduler/core/spreadconstraint.Test_GroupClustersWithScore(0xc0006036c0)
        /Users/didi/OpenSouorce/karmada/pkg/scheduler/core/spreadconstraint/group_clusters_test.go:176 +0x1608
testing.tRunner(0xc0006036c0, 0x102070020)
        /Users/didi/sdk/go1.17.5/src/testing/testing.go:1259 +0x19c
created by testing.(*T).Run
        /Users/didi/sdk/go1.17.5/src/testing/testing.go:1306 +0x5bc
```

**What you expected to happen**:
test successfully.

**How to reproduce it (as minimally and precisely as possible)**:
make test on macos 11.6.5

**Anything else we need to know?**:
Of course, it's bug of gomonkey, https://github.com/agiledragon/gomonkey/issues/77. But it is a bad experience for karmadaer. So shall we remove `gomonkey`?

**Environment**:
- Karmada version: master
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others: `macOS Big Sur  11.6.5`,  `MacBook Pro (13-inch, M1, 2020)`

**Comment by ikaven1024** [comment]
> max_prot=7 is not work after 11.4
> https://gist.github.com/darfink/a756b88e999631d75cbbeefd3eee7e2d

https://github.com/agiledragon/gomonkey/issues/57#issuecomment-919782941

**Comment by RainbowMango** [comment]
> So shall we remove gomonkey?

We haven't been much used this tool.  My answer is yes if we find an alternative way.

**Comment by CharlesQQ** [comment]
I meet the same problem
<img width="232" alt="image" src="https://user-images.githubusercontent.com/18431718/168579226-fec8da2a-e7a8-4eab-967c-b079f192a485.png">
