### ISSUE TITLE
[Good-First] Do not start new tests after the first test failure

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#2073]
**Task description**:
It's a little bit inconvenient to locate the failed cases from a large number of cases. E.g.
https://github.com/karmada-io/karmada/runs/7088769752?check_suite_focus=true

**Solution**:
We can add the `-failfast` flag for `go test` to stop starting new tests after the first test failure. Like:

```diff
diff --git a/Makefile b/Makefile
index bc3cceff..0a894aed 100644
--- a/Makefile
+++ b/Makefile
@@ -110,9 +110,9 @@ release-chart:

 .PHONY: test
 test:
-       go test --race --v ./pkg/...
-       go test --race --v ./cmd/...
-       go test --race --v ./examples/...
+       go test -race -failfast -v ./pkg/...
+       go test -race -failfast -v ./cmd/...
+       go test -race -failfast -v ./examples/...
```
This example also changed `--` to `-` to keep aligned with `go help testflag`.

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by chaunceyjiang** [comment]
@my-git9 The good first issue is intended for first-time contributors to get started on his/her contributor journey.

**Comment by my-git9** [comment]
Sorry, I'll pay attention later

**Comment by ikaven1024** [comment]
We can search `--- FAIL` on the log web to locate the failed test.

Besides, `-v` flag doesn't provide some useful information. Consider dropping it? The log will be shorter much.
```diff
diff --git a/Makefile b/Makefile
index bc3cceff..84c48470 100644
--- a/Makefile
+++ b/Makefile
@@ -110,9 +110,9 @@ release-chart:
 
 .PHONY: test
 test:
-       go test --race --v ./pkg/...
-       go test --race --v ./cmd/...
-       go test --race --v ./examples/...
+       go test --race ./pkg/...
+       go test --race ./cmd/...
+       go test --race ./examples/...
 
 upload-images: images
        @echo "push images to $(REGISTRY)"
```


```
 make test
go test --race ./pkg/...
?   	github.com/karmada-io/karmada/pkg/aggregatedapiserver	[no test files]
?   	github.com/karmada-io/karmada/pkg/apis/cluster	[no test files]
?   	github.com/karmada-io/karmada/pkg/apis/cluster/install	[no test files]
ok  	github.com/karmada-io/karmada/pkg/apis/cluster/v1alpha1	(cached)
ok  	github.com/karmada-io/karmada/pkg/apis/cluster/validation	(cached)
?   	github.com/karmada-io/karmada/pkg/apis/config/v1alpha1	[no test files]
?   	github.com/karmada-io/karmada/pkg/apis/networking/v1alpha1	[no test files]
?   	github.com/karmada-io/karmada/pkg/apis/policy/v1alpha1	[no test files]
?   	github.com/karmada-io/karmada/pkg/apis/search	[no test files]
?   	github.com/karmada-io/karmada/pkg/apis/search/install	[no test files]
?   	github.com/karmada-io/karmada/pkg/apis/search/scheme	[no test files]
?   	github.com/karmada-io/karmada/pkg/apis/search/v1alpha1	[no test files]
?   	github.com/karmada-io/karmada/pkg/apis/work/v1alpha1	[no test files]
ok  	github.com/karmada-io/karmada/pkg/apis/work/v1alpha2	(cached)
?   	github.com/karmada-io/karmada/pkg/clusterdiscovery/clusterapi	[no test files]
?   	github.com/karmada-io/karmada/pkg/controllers/binding	[no test files]
?   	github.com/karmada-io/karmada/pkg/controllers/cluster	[no test files]
ok  	github.com/karmada-io/karmada/pkg/controllers/context	(cached)
?   	github.com/karmada-io/karmada/pkg/controllers/execution	[no test files]
?   	github.com/karmada-io/karmada/pkg/controllers/federatedresourcequota	[no test files]
?   	github.com/karmada-io/karmada/pkg/controllers/hpa	[no test files]
?   	github.com/karmada-io/karmada/pkg/controllers/mcs	[no test files]
?   	github.com/karmada-io/karmada/pkg/controllers/namespace	[no test files]
ok  	github.com/karmada-io/karmada/pkg/controllers/status	(cached)
?   	github.com/karmada-io/karmada/pkg/controllers/unifiedauth	[no test files]
?   	github.com/karmada-io/karmada/pkg/dependenciesdistributor	[no test files]
ok  	github.com/karmada-io/karmada/pkg/descheduler	(cached)
ok  	github.com/karmada-io/karmada/pkg/descheduler/core	(cached)
ok  	github.com/karmada-io/karmada/pkg/detector	(cached)
?   	github.com/karmada-io/karmada/pkg/estimator/client	[no test files]
?   	github.com/karmada-io/karmada/pkg/estimator/pb	[no test files]
ok  	github.com/karmada-io/karmada/pkg/estimator/server	(cached)
?   	github.com/karmada-io/karmada/pkg/estimator/server/metrics	[no test files]
?   	github.com/karmada-io/karmada/pkg/estimator/server/nodes	[no test files]
?   	github.com/karmada-io/karmada/pkg/estimator/server/replica	[no test files]
?   	github.com/karmada-io/karmada/pkg/estimator/service	[no test files]
?   	github.com/karmada-io/karmada/pkg/features	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/clientset/versioned	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/clientset/versioned/fake	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/clientset/versioned/scheme	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/clientset/versioned/typed/cluster/v1alpha1	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/clientset/versioned/typed/cluster/v1alpha1/fake	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/clientset/versioned/typed/config/v1alpha1	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/clientset/versioned/typed/config/v1alpha1/fake	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/clientset/versioned/typed/networking/v1alpha1	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/clientset/versioned/typed/networking/v1alpha1/fake	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/clientset/versioned/typed/policy/v1alpha1	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/clientset/versioned/typed/policy/v1alpha1/fake	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/clientset/versioned/typed/search/v1alpha1	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/clientset/versioned/typed/search/v1alpha1/fake	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/clientset/versioned/typed/work/v1alpha1	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/clientset/versioned/typed/work/v1alpha1/fake	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/clientset/versioned/typed/work/v1alpha2	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/clientset/versioned/typed/work/v1alpha2/fake	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/informers/externalversions	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/informers/externalversions/cluster	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/informers/externalversions/cluster/v1alpha1	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/informers/externalversions/config	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/informers/externalversions/config/v1alpha1	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/informers/externalversions/internalinterfaces	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/informers/externalversions/networking	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/informers/externalversions/networking/v1alpha1	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/informers/externalversions/policy	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/informers/externalversions/policy/v1alpha1	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/informers/externalversions/search	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/informers/externalversions/search/v1alpha1	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/informers/externalversions/work	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/informers/externalversions/work/v1alpha1	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/informers/externalversions/work/v1alpha2	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/listers/cluster/v1alpha1	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/listers/config/v1alpha1	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/listers/networking/v1alpha1	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/listers/policy/v1alpha1	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/listers/search/v1alpha1	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/listers/work/v1alpha1	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/listers/work/v1alpha2	[no test files]
?   	github.com/karmada-io/karmada/pkg/generated/openapi	[no test files]
ok  	github.com/karmada-io/karmada/pkg/karmadactl	(cached)
?   	github.com/karmada-io/karmada/pkg/karmadactl/cmdinit	[no test files]
ok  	github.com/karmada-io/karmada/pkg/karmadactl/cmdinit/cert	(cached)
?   	github.com/karmada-io/karmada/pkg/karmadactl/cmdinit/karmada	[no test files]
?   	github.com/karmada-io/karmada/pkg/karmadactl/cmdinit/kubernetes	[no test files]
?   	github.com/karmada-io/karmada/pkg/karmadactl/cmdinit/options	[no test files]

------------------------------------------------------------------------------------------------------
 █████   ████   █████████   ███████████   ██████   ██████   █████████   ██████████     █████████
░░███   ███░   ███░░░░░███ ░░███░░░░░███ ░░██████ ██████   ███░░░░░███ ░░███░░░░███   ███░░░░░███
 ░███  ███    ░███    ░███  ░███    ░███  ░███░█████░███  ░███    ░███  ░███   ░░███ ░███    ░███
 ░███████     ░███████████  ░██████████   ░███░░███ ░███  ░███████████  ░███    ░███ ░███████████
 ░███░░███    ░███░░░░░███  ░███░░░░░███  ░███ ░░░  ░███  ░███░░░░░███  ░███    ░███ ░███░░░░░███
 ░███ ░░███   ░███    ░███  ░███    ░███  ░███      ░███  ░███    ░███  ░███    ███  ░███    ░███
 █████ ░░████ █████   █████ █████   █████ █████     █████ █████   █████ ██████████   █████   █████
░░░░░   ░░░░ ░░░░░   ░░░░░ ░░░░░   ░░░░░ ░░░░░     ░░░░░ ░░░░░   ░░░░░ ░░░░░░░░░░   ░░░░░   ░░░░░
------------------------------------------------------------------------------------------------------
Karmada is installed successfully.

Register Kubernetes cluster to Karmada control plane.

Register cluster with 'Push' mode

Step 1: Use kubectl karmada join to register the cluster to Karmada control panel. --cluster-kubeconfig is members kubeconfig.
(In karmada)~# MEMBER_CLUSTER_NAME=`cat ~/.kube/config  | grep current-context | sed 's/: /\n/g'| sed '1d'`
(In karmada)~# kubectl karmada --kubeconfig /tmp/karmada-apiserver.config  join ${MEMBER_CLUSTER_NAME} --cluster-kubeconfig=$HOME/.kube/config

Step 2: Show members of karmada
(In karmada)~# kubectl  --kubeconfig /tmp/karmada-apiserver.config get clusters


Register cluster with 'Pull' mode

Step 1:  Send karmada kubeconfig and karmada-agent.yaml to member kubernetes
(In karmada)~# scp /tmp/karmada-apiserver.config /tmp/karmada-agent.yaml {member kubernetes}:~

Step 2:  Create karmada kubeconfig secret
 Notice:
   Cross-network, need to change the config server address.
(In member kubernetes)~#  kubectl create ns karmada-system
(In member kubernetes)~#  kubectl create secret generic karmada-kubeconfig --from-file=karmada-kubeconfig=/root/karmada-apiserver.config  -n karmada-system

Step 3: Create karmada agent
(In member kubernetes)~#  MEMBER_CLUSTER_NAME="demo"
(In member kubernetes)~#  sed -i "s/{member_cluster_name}/${MEMBER_CLUSTER_NAME}/g" karmada-agent.yaml
(In member kubernetes)~#  kubectl apply -f karmada-agent.yaml

Step 4: Show members of karmada
(In karmada)~# kubectl  --kubeconfig /tmp/karmada-apiserver.config get clusters

--- FAIL: TestDownloadFile (30.00s)
panic: Get "https://github.com/karmada-io/karmada/releases/download/v0.9.0/crds.tar.gz": dial tcp 20.205.243.166:443: i/o timeout [recovered]
	panic: Get "https://github.com/karmada-io/karmada/releases/download/v0.9.0/crds.tar.gz": dial tcp 20.205.243.166:443: i/o timeout

goroutine 8 [running]:
testing.tRunner.func1.2({0x10681ab60, 0xc00011e9f0})
	/Users/didi/sdk/go1.18.3/src/testing/testing.go:1389 +0x278
testing.tRunner.func1()
	/Users/didi/sdk/go1.18.3/src/testing/testing.go:1392 +0x420
panic({0x10681ab60, 0xc00011e9f0})
	/Users/didi/sdk/go1.18.3/src/runtime/panic.go:844 +0x258
github.com/karmada-io/karmada/pkg/karmadactl/cmdinit/utils.TestDownloadFile(0x0?)
	/Users/didi/OpenSouorce/karmada/pkg/karmadactl/cmdinit/utils/util_test.go:20 +0x110
testing.tRunner(0xc0003deea0, 0x10695a870)
	/Users/didi/sdk/go1.18.3/src/testing/testing.go:1439 +0x190
created by testing.(*T).Run
	/Users/didi/sdk/go1.18.3/src/testing/testing.go:1486 +0x564
FAIL	github.com/karmada-io/karmada/pkg/karmadactl/cmdinit/utils	30.317s
?   	github.com/karmada-io/karmada/pkg/karmadactl/options	[no test files]
ok  	github.com/karmada-io/karmada/pkg/printers	(cached)
ok  	github.com/karmada-io/karmada/pkg/printers/internalversion	(cached)
?   	github.com/karmada-io/karmada/pkg/printers/storage	[no test files]
?   	github.com/karmada-io/karmada/pkg/registry/cluster	[no test files]
?   	github.com/karmada-io/karmada/pkg/registry/cluster/storage	[no test files]
?   	github.com/karmada-io/karmada/pkg/registry/search	[no test files]
ok  	github.com/karmada-io/karmada/pkg/registry/search/storage	(cached)
?   	github.com/karmada-io/karmada/pkg/resourceinterpreter	[no test files]
?   	github.com/karmada-io/karmada/pkg/resourceinterpreter/customizedinterpreter	[no test files]
?   	github.com/karmada-io/karmada/pkg/resourceinterpreter/customizedinterpreter/configmanager	[no test files]
?   	github.com/karmada-io/karmada/pkg/resourceinterpreter/customizedinterpreter/webhook	[no test files]
ok  	github.com/karmada-io/karmada/pkg/resourceinterpreter/defaultinterpreter	(cached)
?   	github.com/karmada-io/karmada/pkg/resourceinterpreter/defaultinterpreter/prune	[no test files]
ok  	github.com/karmada-io/karmada/pkg/scheduler	(cached)
?   	github.com/karmada-io/karmada/pkg/scheduler/cache	[no test files]
ok  	github.com/karmada-io/karmada/pkg/scheduler/core	(cached)
ok  	github.com/karmada-io/karmada/pkg/scheduler/core/spreadconstraint	(cached)
?   	github.com/karmada-io/karmada/pkg/scheduler/framework	[no test files]
?   	github.com/karmada-io/karmada/pkg/scheduler/framework/plugins	[no test files]
?   	github.com/karmada-io/karmada/pkg/scheduler/framework/plugins/apiinstalled	[no test files]
?   	github.com/karmada-io/karmada/pkg/scheduler/framework/plugins/clusteraffinity	[no test files]
?   	github.com/karmada-io/karmada/pkg/scheduler/framework/plugins/clusterlocality	[no test files]
?   	github.com/karmada-io/karmada/pkg/scheduler/framework/plugins/spreadconstraint	[no test files]
?   	github.com/karmada-io/karmada/pkg/scheduler/framework/plugins/tainttoleration	[no test files]
?   	github.com/karmada-io/karmada/pkg/scheduler/framework/runtime	[no test files]
?   	github.com/karmada-io/karmada/pkg/scheduler/metrics	[no test files]
?   	github.com/karmada-io/karmada/pkg/search	[no test files]
?   	github.com/karmada-io/karmada/pkg/search/backendstore	[no test files]
?   	github.com/karmada-io/karmada/pkg/sharedcli	[no test files]
?   	github.com/karmada-io/karmada/pkg/sharedcli/klogflag	[no test files]
?   	github.com/karmada-io/karmada/pkg/sharedcli/ratelimiterflag	[no test files]
ok  	github.com/karmada-io/karmada/pkg/util	(cached)
?   	github.com/karmada-io/karmada/pkg/util/gclient	[no test files]
?   	github.com/karmada-io/karmada/pkg/util/hash	[no test files]
ok  	github.com/karmada-io/karmada/pkg/util/helper	(cached)
ok  	github.com/karmada-io/karmada/pkg/util/imageparser	(cached)
?   	github.com/karmada-io/karmada/pkg/util/informermanager	[no test files]
ok  	github.com/karmada-io/karmada/pkg/util/informermanager/keys	(cached)
ok  	github.com/karmada-io/karmada/pkg/util/interpreter	(cached)
ok  	github.com/karmada-io/karmada/pkg/util/lifted	(cached)
?   	github.com/karmada-io/karmada/pkg/util/metrics	[no test files]
ok  	github.com/karmada-io/karmada/pkg/util/names	(cached)
?   	github.com/karmada-io/karmada/pkg/util/objectwatcher	[no test files]
ok  	github.com/karmada-io/karmada/pkg/util/overridemanager	(cached)
?   	github.com/karmada-io/karmada/pkg/util/restmapper	[no test files]
ok  	github.com/karmada-io/karmada/pkg/util/validation	(cached)
ok  	github.com/karmada-io/karmada/pkg/version	(cached)
?   	github.com/karmada-io/karmada/pkg/version/sharedcommand	[no test files]
?   	github.com/karmada-io/karmada/pkg/webhook/clusteroverridepolicy	[no test files]
?   	github.com/karmada-io/karmada/pkg/webhook/clusterpropagationpolicy	[no test files]
ok  	github.com/karmada-io/karmada/pkg/webhook/configuration	(cached)
ok  	github.com/karmada-io/karmada/pkg/webhook/federatedresourcequota	(cached)
?   	github.com/karmada-io/karmada/pkg/webhook/interpreter	[no test files]
?   	github.com/karmada-io/karmada/pkg/webhook/overridepolicy	[no test files]
?   	github.com/karmada-io/karmada/pkg/webhook/propagationpolicy	[no test files]
?   	github.com/karmada-io/karmada/pkg/webhook/work	[no test files]
FAIL
make: *** [test] Error 1
```

**Comment by RainbowMango** [comment]
> Besides, -v flag doesn't provide some useful information. Consider dropping it?  The log will be shorter much.

Postpone this until we really need it.

/close
