### ISSUE TITLE
Install Karmada v1.3 by local-up-karmada failed

### ISSUE THREAD

**Issue by Poor12** [karmada-io/karmada#2951]
**What happened**:
Install Karmada v1.3 by local-up-karmada failed, v1.4 is ok.
Log is like:
```
go install github.com/cloudflare/cfssl/cmd/...@v1.5.0
Generating a RSA private key
.......+++++
..................................................................................................................................+++++
writing new private key to '/root/.karmada/ca.key'
-----
Generating a RSA private key
...............................+++++
..............+++++
writing new private key to '/root/.karmada/front-proxy-ca.key'
-----
Generating a RSA private key
......................................+++++
.............................................................................+++++
writing new private key to '/root/.karmada/etcd-ca.key'
-----
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8bacc6]

goroutine 1 [running]:
debug/elf.(*Section).ReadAt(0xc0000aa370?, {0xc0003ecc00?, 0x11b2d08?, 0x30?}, 0x40?)
        <autogenerated>:1 +0x26
archive/zip.readDirectoryEnd({0xbe8520, 0xc0000f3980}, 0x5b0)
        /usr/local/go/src/archive/zip/reader.go:526 +0xf5
archive/zip.(*Reader).init(0xc0002b73b0, {0xbe8520?, 0xc0000f3980}, 0x5b0)
        /usr/local/go/src/archive/zip/reader.go:97 +0x5c
archive/zip.NewReader({0xbe8520, 0xc0000f3980}, 0x5b0)
        /usr/local/go/src/archive/zip/reader.go:90 +0x5e
github.com/daaku/go%2ezipexe.zipExeReaderElf({0xbe92a0?, 0xc0000140f0}, 0x11b3908)
        /root/go/pkg/mod/github.com/daaku/go.zipexe@v1.0.0/zipexe.go:128 +0x8b
github.com/daaku/go%2ezipexe.NewReader({0xbe92a0, 0xc0000140f0}, 0x0?)
        /root/go/pkg/mod/github.com/daaku/go.zipexe@v1.0.0/zipexe.go:48 +0x98
github.com/daaku/go%2ezipexe.OpenCloser({0xc00003c288?, 0xc0001c9be0?})
        /root/go/pkg/mod/github.com/daaku/go.zipexe@v1.0.0/zipexe.go:30 +0x57
github.com/GeertJohan/go%2erice.init.0()
        /root/go/pkg/mod/github.com/!geert!johan/go.rice@v1.0.0/appended.go:41 +0x65
Failed to parse input: unexpected end of JSON input
```

**What you expected to happen**:
Install succeed.

**How to reproduce it (as minimally and precisely as possible)**:
Install Karmada v1.3 by local-up-karmada

**Anything else we need to know?**:

**Environment**:
- Karmada version: v1.3
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others: ubuntu

**Comment by RainbowMango** [comment]
https://github.com/karmada-io/karmada/pull/2462
