### ISSUE TITLE
FederatedHPA custom metrics not ok

### ISSUE THREAD

**Issue by 13567436138** [karmada-io/karmada#4692]
```


^C
root@karmada-01-b:~/karmada-teaching/1.6-feature# kubectl logs -n karmada-system karmada-metrics-adapter-bc765dcf9-mfvqd -f
I0309 08:45:32.240839       1 options.go:114] karmada-metrics-adapter version: version.Info{GitVersion:"v1.9.0", GitCommit:"a03aa846cfd2c1978b166660d6f592a1c10aeb3d", GitTreeState:"clean", BuildDate:"2024-02-29T08:15:36Z", GoVersion:"go1.20.11", Compiler:"gc", Platform:"linux/amd64"}
I0309 08:45:33.085948       1 handler.go:275] Adding GroupVersion metrics.k8s.io v1beta1 to ResourceManager
I0309 08:45:33.126446       1 secure_serving.go:213] Serving securely on [::]:443
I0309 08:45:33.127183       1 requestheader_controller.go:169] Starting RequestHeaderAuthRequestController
I0309 08:45:33.128007       1 shared_informer.go:311] Waiting for caches to sync for RequestHeaderAuthRequestController
I0309 08:45:33.128210       1 dynamic_serving_content.go:132] "Starting controller" name="serving-cert::/etc/kubernetes/pki/karmada.crt::/etc/kubernetes/pki/karmada.key"
I0309 08:45:33.128464       1 tlsconfig.go:240] "Starting DynamicServingCertificateController"
I0309 08:45:33.138942       1 configmap_cafile_content.go:202] "Starting controller" name="client-ca::kube-system::extension-apiserver-authentication::client-ca-file"
I0309 08:45:33.139147       1 shared_informer.go:311] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I0309 08:45:33.139375       1 configmap_cafile_content.go:202] "Starting controller" name="client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file"
I0309 08:45:33.139556       1 shared_informer.go:311] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I0309 08:45:33.228635       1 shared_informer.go:318] Caches are synced for RequestHeaderAuthRequestController
I0309 08:45:33.240338       1 shared_informer.go:318] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I0309 08:45:33.241051       1 shared_informer.go:318] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
W0309 08:45:33.246414       1 reflector.go:535] pkg/generated/informers/externalversions/factory.go:139: failed to list *v1alpha1.Cluster: the server is currently unable to handle the request (get clusters.cluster.karmada.io)
E0309 08:45:33.246677       1 reflector.go:147] pkg/generated/informers/externalversions/factory.go:139: Failed to watch *v1alpha1.Cluster: failed to list *v1alpha1.Cluster: the server is currently unable to handle the request (get clusters.cluster.karmada.io)
W0309 08:45:34.114501       1 reflector.go:535] pkg/generated/informers/externalversions/factory.go:139: failed to list *v1alpha1.Cluster: the server is currently unable to handle the request (get clusters.cluster.karmada.io)
E0309 08:45:34.114730       1 reflector.go:147] pkg/generated/informers/externalversions/factory.go:139: Failed to watch *v1alpha1.Cluster: failed to list *v1alpha1.Cluster: the server is currently unable to handle the request (get clusters.cluster.karmada.io)
W0309 08:45:36.042830       1 reflector.go:535] pkg/generated/informers/externalversions/factory.go:139: failed to list *v1alpha1.Cluster: the server is currently unable to handle the request (get clusters.cluster.karmada.io)
E0309 08:45:36.043130       1 reflector.go:147] pkg/generated/informers/externalversions/factory.go:139: Failed to watch *v1alpha1.Cluster: failed to list *v1alpha1.Cluster: the server is currently unable to handle the request (get clusters.cluster.karmada.io)
W0309 08:45:40.171106       1 reflector.go:535] pkg/generated/informers/externalversions/factory.go:139: failed to list *v1alpha1.Cluster: the server is currently unable to handle the request (get clusters.cluster.karmada.io)
E0309 08:45:40.171340       1 reflector.go:147] pkg/generated/informers/externalversions/factory.go:139: Failed to watch *v1alpha1.Cluster: failed to list *v1alpha1.Cluster: the server is currently unable to handle the request (get clusters.cluster.karmada.io)
W0309 08:51:04.811323       1 controller.go:165] cluster member1 is notReady try to stop this cluster informer
E0309 08:51:05.499261       1 custommetrics.go:296] failed to get MultiClusterDiscovery for cluster(member1)
E0309 08:51:05.505932       1 custommetrics.go:296] failed to get MultiClusterDiscovery for cluster(member1)
E0309 08:51:05.507733       1 custommetrics.go:296] failed to get MultiClusterDiscovery for cluster(member1)
E0309 08:51:05.509309       1 custommetrics.go:296] failed to get MultiClusterDiscovery for cluster(member1)
E0309 08:51:05.510818       1 custommetrics.go:296] failed to get MultiClusterDiscovery for cluster(member1)
E0309 08:51:05.513129       1 custommetrics.go:296] failed to get MultiClusterDiscovery for cluster(member1)
E0309 08:51:05.515265       1 custommetrics.go:296] failed to get MultiClusterDiscovery for cluster(member1)
E0309 08:51:05.516634       1 custommetrics.go:296] failed to get MultiClusterDiscovery for cluster(member1)
E0309 08:51:05.517909       1 custommetrics.go:296] failed to get MultiClusterDiscovery for cluster(member1)
E0309 08:51:05.519206       1 custommetrics.go:296] failed to get MultiClusterDiscovery for cluster(member1)
I0309 08:51:06.327668       1 controller.go:172] Try to build informer manager for cluster member1
[controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.
Detected at:
        >  goroutine 226 [running]:
        >  runtime/debug.Stack()
        >       /opt/hostedtoolcache/go/1.20.11/x64/src/runtime/debug/stack.go:24 +0x65
        >  sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
        >       /home/runner/work/karmada/karmada/vendor/sigs.k8s.io/controller-runtime/pkg/log/log.go:60 +0xcd
        >  sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).WithName(0xc0003bdbc0, {0x26aa470, 0x14})
        >       /home/runner/work/karmada/karmada/vendor/sigs.k8s.io/controller-runtime/pkg/log/deleg.go:147 +0x4c
        >  github.com/go-logr/logr.Logger.WithName({{0x2b19438, 0xc0003bdbc0}, 0x0}, {0x26aa470?, 0x63?})
        >       /home/runner/work/karmada/karmada/vendor/github.com/go-logr/logr/logr.go:336 +0x46
        >  sigs.k8s.io/controller-runtime/pkg/client.newClient(0xc0009d9c28?, {0x0, 0xc0001a2c40, {0x0, 0x0}, 0x0, {0x0, 0x0}, 0x0})
        >       /home/runner/work/karmada/karmada/vendor/sigs.k8s.io/controller-runtime/pkg/client/client.go:122 +0xff
        >  sigs.k8s.io/controller-runtime/pkg/client.New(0xc000000000?, {0x0, 0xc0001a2c40, {0x0, 0x0}, 0x0, {0x0, 0x0}, 0x0})
        >       /home/runner/work/karmada/karmada/vendor/sigs.k8s.io/controller-runtime/pkg/client/client.go:103 +0x85
        >  github.com/karmada-io/karmada/pkg/util/gclient.NewForConfig(...)
        >       /home/runner/work/karmada/karmada/pkg/util/gclient/gclient.go:64
        >  github.com/karmada-io/karmada/pkg/util/gclient.NewForConfigOrDie(0xc000c26957?)
        >       /home/runner/work/karmada/karmada/pkg/util/gclient/gclient.go:72 +0x59
        >  github.com/karmada-io/karmada/pkg/metricsadapter.(*MetricsController).handleClusters(0xc00012d200)
        >       /home/runner/work/karmada/karmada/pkg/metricsadapter/controller.go:173 +0x619
        >  github.com/karmada-io/karmada/pkg/metricsadapter.(*MetricsController).worker(...)
        >       /home/runner/work/karmada/karmada/pkg/metricsadapter/controller.go:132
        >  k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0009d9f00?)
        >       /home/runner/work/karmada/karmada/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:226 +0x3e
        >  k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0?, {0x2aefd20, 0xc000bff8f0}, 0x1, 0xc00054a540)
        >       /home/runner/work/karmada/karmada/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:227 +0xb6
        >  k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0009f7fb0?, 0x3b9aca00, 0x0, 0x0?, 0x0?)
        >       /home/runner/work/karmada/karmada/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:204 +0x89
        >  k8s.io/apimachinery/pkg/util/wait.Until(0xa886ea?, 0x54532a?, 0x1c?)
        >       /home/runner/work/karmada/karmada/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:161 +0x25
        >  created by github.com/karmada-io/karmada/pkg/metricsadapter.(*MetricsController).startController
        >       /home/runner/work/karmada/karmada/pkg/metricsadapter/controller.go:121 +0xc5
W0309 08:51:19.083064       1 controller.go:165] cluster member2 is notReady try to stop this cluster informer
I0309 08:51:20.083558       1 controller.go:172] Try to build informer manager for cluster member2
E0309 08:55:36.446694       1 wrap.go:54] timeout or abort while handling: method=GET URI="/apis/custom.metrics.k8s.io/v1beta2" audit-ID="38391507-d0e6-4015-88ff-d97dae4f6287"
E0309 08:55:36.447007       1 wrap.go:54] timeout or abort while handling: method=GET URI="/apis/custom.metrics.k8s.io/v1beta1" audit-ID="527ecb50-b739-4f41-be0c-fdc703177bf7"
E0309 08:55:36.447179       1 timeout.go:142] post-timeout activity - time-elapsed: 15.472µs, GET "/apis/custom.metrics.k8s.io/v1beta1" result: <nil>
E0309 08:55:36.447296       1 wrap.go:54] timeout or abort while handling: method=GET URI="/apis/custom.metrics.k8s.io/v1beta2" audit-ID="f12e0b8d-3753-4393-876f-55215820d9f6"
E0309 08:55:36.447387       1 timeout.go:142] post-timeout activity - time-elapsed: 3.556µs, GET "/apis/custom.metrics.k8s.io/v1beta2" result: <nil>
E0309 08:55:36.447466       1 wrap.go:54] timeout or abort while handling: method=GET URI="/apis/custom.metrics.k8s.io/v1beta2" audit-ID="39a7b865-4f62-499f-abd0-82e8f70018a8"
E0309 08:55:36.447523       1 timeout.go:142] post-timeout activity - time-elapsed: 2.583µs, GET "/apis/custom.metrics.k8s.io/v1beta2" result: <nil>
E0309 08:55:36.447977       1 timeout.go:142] post-timeout activity - time-elapsed: 3.152µs, GET "/apis/custom.metrics.k8s.io/v1beta2" result: <nil>
E0309 09:02:36.364168       1 writers.go:122] apiserver was unable to write a JSON response: http2: stream closed
E0309 09:02:36.365924       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}: http2: stream closed
E0309 09:02:36.367608       1 writers.go:135] apiserver was unable to write a fallback JSON response: http2: stream closed
E0309 09:02:36.368921       1 writers.go:122] apiserver was unable to write a JSON response: http2: stream closed
E0309 09:02:36.369877       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}: http2: stream closed
E0309 09:02:36.370902       1 wrap.go:54] timeout or abort while handling: method=GET URI="/apis/custom.metrics.k8s.io/v1beta1" audit-ID="1881d366-d6c5-459a-ab4b-cf26ebc5cdca"
E0309 09:02:36.371744       1 writers.go:135] apiserver was unable to write a fallback JSON response: http2: stream closed
E0309 09:02:36.372584       1 wrap.go:54] timeout or abort while handling: method=GET URI="/apis/custom.metrics.k8s.io/v1beta1" audit-ID="ad15bedf-7607-4efc-8693-0fb2ba9b4617"
E0309 09:02:36.372616       1 timeout.go:142] post-timeout activity - time-elapsed: 3.774µs, GET "/apis/custom.metrics.k8s.io/v1beta1" result: <nil>
E0309 09:02:36.372724       1 timeout.go:142] post-timeout activity - time-elapsed: 92.953µs, GET "/apis/custom.metrics.k8s.io/v1beta1" result: <nil>
```

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

```
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm pull prometheus-community/prometheus-adapter


helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm pull prometheus-community/kube-prometheus-stack


kubectl create ns monitoring --kubeconfig ~/kube-karmada

helm install kps ./ -n monitoring --create-namespace --kubeconfig ~/.kube/185config
helm install kps ./ -n monitoring --create-namespace --kubeconfig ~/.kube/182config

helm install prometheus-adapter ./  -n monitoring --kubeconfig ~/.kube/185config
helm install prometheus-adapter ./  -n monitoring --kubeconfig ~/.kube/182config

把crd部署到karmada

kubectl create  -f charts/crds/crds/ --kubeconfig ~/kube-karmada 



或者:
git clone https://github.com/prometheus-operator/kube-prometheus.git
cd kube-prometheus
kubectl apply --server-side -f manifests/setup  --kubeconfig ~/.kube/182config
kubectl wait \
    --for condition=Established \
    --all CustomResourceDefinition \
    --namespace=monitoring  --kubeconfig ~/.kube/182config
kubectl apply -f manifests/  --kubeconfig ~/.kube/182config

```

deploy-svc-pp-sample.yaml

kubectl apply -f deploy-svc-pp-sample.yaml -n karmada --kubeconfig ~/kube-karmada

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  labels:
    app: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/hxpdocker/autoscale-demo:v0.1.2
        name: metrics-provider
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-app
  name: sample-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: sample-app
  type: ClusterIP
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: app-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: sample-app
    - apiVersion: v1
      kind: Service
      name: sample-app
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        staticWeightList:
          - targetCluster:
              clusterNames:
                - member1
            weight: 1
          - targetCluster:
              clusterNames:
                - member2
            weight: 1
```

After deploying, you can check the distribution of the pods and service:

```sh
root@karmada-01-b:~/karmada-teaching/1.6-feature# karmadactl get pods -n karmada --kubeconfig ~/kube-karmada 
NAME                          CLUSTER   READY   STATUS    RESTARTS   AGE
sample-app-697b9b8869-z82w5   member2   1/1     Running   0          27s
oot@karmada-01-b:~/karmada-teaching/1.6-feature# karmadactl get svc -n karmada --kubeconfig ~/kube-karmada 
NAME         CLUSTER   TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE   ADOPTION
sample-app   member2   ClusterIP   10.70.163.208   <none>        80/TCP    45s   Y
sample-app   member1   ClusterIP   10.69.157.46    <none>        80/TCP    45s   Y
```

In order to monitor your application, you'll need to set up a ServiceMonitor pointing at the application. Assuming you've set up your Prometheus instance to use ServiceMonitors with the app: sample-app label, create a ServiceMonitor to monitor the app's metrics via the service:

serviceMonitor-sample.yaml

kubectl apply -f serviceMonitor-sample.yaml   -n karmada --kubeconfig ~/kube-karmada

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sample-app
  labels:
    app: sample-app
    release: kps
spec:
  selector:
    matchLabels:
      app: sample-app
  endpoints:
  - port: http
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: sm-sample-app
spec:
  resourceSelectors:
    - apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      name: sample-app
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
```

Now, you should see your metrics (http_requests_total) appear in your Prometheus instance. Look them up via the dashboard, and make sure they have the namespace and pod labels. If not, check the labels on the service monitor match the ones on the Prometheus CRD.

After you deploy `prometheus-adapter`, you need to update to the adapter config which is necessary in order to expose custom metrics.

这段代码是一个Kubernetes的ConfigMap资源定义，它通常用来存储配置数据。ConfigMap可以用来保存配置文件、命令行参数、环境变量等，以供Kubernetes中的其他资源如pods使用。

在你提供的这段代码中，ConfigMap名为`adapter-config`，位于`monitoring`命名空间。ConfigMap中包含了一个名为`config.yaml`的键，其值是一个多行的字符串，看起来像是用于配置某个监控适配器的YAML格式的配置文件。

让我们逐个部分分析`config.yaml`的内容：

- `"rules"`: 这部分定义了一个规则数组，每个规则用于配置如何查询和转换监控数据。
- `- "seriesQuery": |`: 这里定义了一个查询表达式，用于选择监控时间序列。`{namespace!="",__name__!~"^container_.*"}`这个PromQL表达式的意思是选择所有命名空间非空且指标名称不以`container_`开头的时间序列。
- `"resources"`: 指定了如何将选中的时间序列映射到Kubernetes资源上。
  - `"template": "<<.Resource>>"`: 这里使用了一个模板，`<<.Resource>>`可能会被替换为具体的Kubernetes资源名称。
- `"name"`: 定义了如何重命名时间序列。
  - `"matches": "^(.*)_total"`: 使用正则表达式来匹配指标名称，匹配到的将会被处理。
  - `"as": ""`: 重命名匹配到的指标名称。这里没有指定新名称，所以它可能会保留原始名称或者根据上下文来处理。
- `"metricsQuery": |`: 定义了如何构建用于检索指标数据的查询。
  - `sum by (<<.GroupBy>>) (`: 使用`sum`函数按照指定的标签（`<<.GroupBy>>`）对时间序列求和。
  - `irate (<<.Series>>{<<.LabelMatchers>>}[1m])`: 计算每个系列在最近1分钟内每秒的平均增长率。

这个配置可能是用于Prometheus适配器的，该适配器可以将Prometheus查询转换为与Kubernetes资源相关联的指标。适配器会根据这个ConfigMap中定义的规则来转换并输出监控指标。这在自定义监控和告警规则时非常有用，尤其是当你想要监控特定资源或根据特定逻辑聚合指标时。

请注意，配置文件中使用的`<< >>`可能是该适配器特定的模板表示法，用于在运行时替换为实际的值。这不是标准的YAML语法，所以这个配置文件很可能是专门为某个工具或应用程序定制的。

cm-adapter-config.yaml

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-adapter
  #name: adapter-config
  namespace: monitoring
data:
  config.yaml: |-
    "rules":
    - "seriesQuery": |
         {namespace!="",__name__!~"^container_.*"}
      "resources":
        "template": "<<.Resource>>"
      "name":
        "matches": "^(.*)_total"
        "as": ""
      "metricsQuery": |
        sum by (<<.GroupBy>>) (
          irate (
            <<.Series>>{<<.LabelMatchers>>}[1m]
          )
        )
```

```text
kubectl apply -f cm-adapter-config.yaml -n monitoring --kubeconfig ~/.kube/182config
kubectl apply -f cm-adapter-config.yaml -n monitoring --kubeconfig ~/.kube/185config

kubectl rollout restart deployment/prometheus-adapter -n monitoring  --kubeconfig ~/.kube/182config
kubectl rollout restart deployment/prometheus-adapter -n monitoring  --kubeconfig ~/.kube/185config
```

You also need to register the custom metrics API with the API aggregator (part of the main Kubernetes API server). For that you need to create an APIService resource.

kubectl apply  -f api-service.yaml --kubeconfig ~/.kube/182config

kubectl apply  -f api-service.yaml --kubeconfig ~/.kube/185config

```yaml
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta2.custom.metrics.k8s.io
spec:
  group: custom.metrics.k8s.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: prometheus-adapter
    namespace: monitoring
    port: 443
  version: v1beta2
  versionPriority: 100
```

The API is registered as `custom.metrics.k8s.io/v1beta2`, and you can use the following command to verify:

```text
kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta2/namespaces/karmada/pods/*/http_requests?selector=app%3Dsample-app"
```

The output is similar to:

```text
oot@karmada-03-a:~# kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta2/namespaces/karmada/pods/*/http_requests?selector=app%3Dsample-app"
{"kind":"MetricValueList","apiVersion":"custom.metrics.k8s.io/v1beta2","metadata":{},"items":[{"describedObject":{"kind":"Pod","namespace":"karmada","name":"sample-app-697b9b8869-z82w5","apiVersion":"/v1"},"metric":{"name":"http_requests","selector":null},"timestamp":"2024-03-08T08:00:07Z","value":"33m"}]}
```

If `karmada-metrics-adapter` is installed successfully, you can also verify it with the above command in Karmada control plane.

Then let's deploy FederatedHPA in Karmada control plane.

federatedHPA-metrics-External-name.yaml

kubectl apply -f federatedHPA-metrics-External-name.yaml  -n karmada --kubeconfig ~/kube-karmada

```yaml
apiVersion: autoscaling.karmada.io/v1alpha1
kind: FederatedHPA
metadata:
  name: sample-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-app
  minReplicas: 1
  maxReplicas: 10
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 10
    scaleUp:
      stabilizationWindowSeconds: 10
  metrics:
    - type: External
      pods:
        metric:
          name: http_requests
        target:
          averageValue: 700m
          type: Value
```

After deploying, you can check the FederatedHPA:

```sh
NAME          REFERENCE-KIND   REFERENCE-NAME   MINPODS   MAXPODS   REPLICAS   AGE
sample-app    Deployment       sample-app       1         10        1          15d
```

multiClusterService-sample.yaml

kubectl apply -f multiClusterService-sample.yaml -n karmada --kubeconfig ~/kube-karmada

```
---
apiVersion: networking.karmada.io/v1alpha1
kind: MultiClusterService
metadata:
   name: sample-app
spec:
   types:
   - CrossCluster
   serviceProvisionClusters:
   - cluster1
   - cluster2
   serviceConsumptionClusters:
   - cluster1
```

压测：

```
hey -c 100 -z 1m http://10.69.18.128
```

清理：

```
kubectl delete -f multiClusterService-sample.yaml -n karmada --kubeconfig ~/kube-karmada
kubectl delete -f federatedHPA-metrics-External-name.yaml  -n karmada --kubeconfig ~/kube-karmada
kubectl delete -f api-service.yaml --kubeconfig ~/.kube/182config
kubectl delete -f api-service.yaml --kubeconfig ~/.kube/185config
kubectl delete -f serviceMonitor-sample.yaml   -n karmada --kubeconfig ~/kube-karmada
kubectl delete -f deploy-svc-pp-sample.yaml -n karmada --kubeconfig ~/kube-karmada
```

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by Orfeasfil** [comment]
Same problem here.. Any answer?
